[package]
name = "coreipc"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

tokio.workspace = true
rand = "0.8.5"
libc.workspace = true

[dev-dependencies]
temp-env = "0.3.6"
tempfile = "3.15.0"
