[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = [
    "piguycs <piguycs@pm.me>"
]

[workspace.dependencies]
# tracing
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }

# async
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "io-std", "io-util", "net", "sync"] }
tokio-util = { version = "0.7.13", features = ["compat"] }

rand = { version = "0.8.5" }

s2n-quic = "1"

# networking
tun = "0.7.10"
etherparse = "0.16.0"

# dependencies from this workspace
coreipc = { path = "crates/coreipc" }

# libc for accessing linux specific APIs
# any version is fine, libc underneath wont change
libc = { version = "*" }

thiserror = { version = "2.0.9" }

# serialisation of data (used for coreipc)
# might move this to coreipc
serde = { version = "1.0.217", features = ["derive"]}
bincode = { version = "1.3.3" }
