[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = [
    "piguycs <piguycs@pm.me>"
]

[workspace.dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }

s2n-quic = "1"

tun = "0.7.10" # TODO: switch to tokio-tun for linux
etherparse = "0.16.0"

tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "io-std", "io-util", "net", "sync"] }

# dependencies from this workspace
coreipc = { path = "crates/coreipc" }

# libc for accessing linux specific APIs
libc = "*"
