[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = [
    "piguycs <piguycs@pm.me>"
]

[workspace.dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }

s2n-quic = "1"

tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }

# dependencies from this workspace
protoipc = { path = "crates/protoipc" }
