[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = [
    "piguycs <piguycs@pm.me>"
]

[workspace.dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }

# dependencies from this workspace
protoipc = { path = "crates/protoipc" }
