[package]
name = "ls-daemon"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

tokio.workspace = true

tun.workspace = true

s2n-quic.workspace = true

# coreipc.workspace = true
